import { Reveal } from "@/components/reveal";
import { SectionHeading } from "@/components/section-heading";

const days = [
  { date: "May 19", day: "Day 1", events: [{ time: "17:00 - 20:00", title: "Lectures & Workshops" }] },
  { date: "May 20", day: "Day 2", events: [{ time: "All Day", title: "Company Fair" }, { time: "Morning & Afternoon", title: "Interviews & Speed Interviews" }, { time: "End of Day", title: "Informal Business Networking Snack" }] },
  { date: "May 21", day: "Day 3", events: [{ time: "17:00 - 20:00", title: "Lectures & Workshops" }, { time: "After 20:00", title: "Closing Session & Networking" }] },
];
export function Timeline() { return <section id="timeline" className="border-t border-border px-6 py-24 sm:py-28"><div className="mx-auto max-w-6xl"><SectionHeading eyebrow="Schedule" title="event timeline" description="The full detailed schedule is coming soon. Stay tuned!" index="03 / 05" /><div className="relative"><div aria-hidden="true" className="absolute left-0 right-0 top-[7px] hidden h-px bg-border md:block" /><div className="grid gap-10 md:grid-cols-3 md:gap-8">{days.map((day, index) => <Reveal key={day.day} delay={index * 120}><article className="group relative"><div aria-hidden="true" className="relative z-10 mb-8 hidden h-4 w-4 border-[3px] border-accent bg-background transition-transform duration-200 group-hover:scale-125 md:block" /><div className="border-t border-border pt-6 md:border-t-0 md:pt-0"><p className="font-display text-xs uppercase tracking-[0.2em] text-accent">{day.day}</p><h3 className="mt-2 font-display text-3xl lowercase tracking-[0.1em] text-primary">{day.date}</h3><ul className="mt-7 space-y-5">{day.events.map((event) => <li key={event.title} className="border-l-2 border-accent/25 pl-4 transition-colors duration-200 group-hover:border-accent/50"><span className="font-display text-base text-muted-foreground">{event.time}</span><p className="mt-1 text-sm leading-relaxed text-secondary-foreground">{event.title}</p></li>)}</ul></div></article></Reveal>)}</div></div></div></section>; }
